### PR TITLE
Allow CELERY_CONFIG module to be set

### PR DESCRIPTION
**Pull request by immunda**
Rather than adding support for various types of config params through endless `ENV` variables, I thought it would be easier to specify a configuration module, which could be added as a volume.

Whilst I was there I also changed the user and `WORKDIR` to something that felt more intuitive (as most people will probably be mounting their own tasks to `/celery`).

An example use-case I had in mind: `docker run --rm -it -v /some/tasks:/celery -e "CELERY_CONFIG=config.qa" celery`

The only confusion I could foresee would be if somebody set `BROKER_URL` in their configuration module and additionally the `CELERY_BROKER_URL` envvar, where `BROKER_URL` would win out.

Thanks, Phil.

### CODE REVIEW

**Comment by tianon** [comment]
What's the advantage to this over just bind-mounting your config file over the top of the one in the container, or making a simple `Dockerfile` that's `FROM celery` and does `COPY` or `RUN` to add custom configuration?  Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with custom config.

**Comment by immunda** [comment]
My motivation at the time was to be able to have multiple environments switchable from the base image given a single mounted volume, which would remove the requirement to have a potentially stale `FROM celery` child image. As you point out though, a repository with a custom `COPY` or/or `RUN` and link to the parent `celery` image would resolve that though.

One thing I believe this change does still address is an undesirable behaviour where a `BROKER_URL` provided in `celeryconfig.py` will be overridden by the `CELERY_BROKER_URL` envvar by default. This leads to splitting configuration management between both `celeryconfig.py` and through having to set the envvar. Would you like me to create a PR or issue separately for that, or is this for a use case I'm not seeing?

**Comment by yosifkit** [comment]
The override from the environment variable only happens in the provided config file, if a user provides their own config file, then the value of `CELERY_BROKER_URL` will not matter.

**Comment by immunda** [comment]
Perhaps this is more of a Celery problem, but unfortunately there's undocumented behaviour where `CELERY_BROKER_URL` envvar will _always_ trump `BROKER_URL` as provided in a config file, as can be seen at https://github.com/celery/celery/blob/master/celery/app/utils.py#L106 which I believe results in the behaviour I encountered above.

There's a similar issue already been raised with Celery months ago https://github.com/celery/celery/issues/2765, but in the meantime I wonder if there's a way of restructuring this Dockerfile to avoid confusion?

**Comment by yosifkit** [comment]
Oh, then it seems reasonable to use a different environment variable name, or just get rid of the variable and put the value in the config file since users can just use `CELERY_BROKER_URL` anyway and it should just work.

**Comment by immunda** [comment]
Sounds ideal :+1:

**Comment by tianon** [comment]
`ENV CELERY_BROKER_URL=` or `-e CELERY_BROKER_URL=` will reset this property too, but I'm +1 to updating our default config to just set the default value and let Celery handle the env var override.

**Comment by tianon** [comment]
I was going through old PRs, and ended up filing https://github.com/docker-library/celery/issues/12 as a result -- if you've got time, please go check my assumptions before we deprecate this image entirely. :heart: :pray:

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/880 for more details of the deprecation of this image.

**Pull request closed without merging**
